In [1]:
import numpy as np

In [2]:
#Pass matrix
A = np.matrix([[0.25, 0.20, 0.1], [0.1, 0.25, 0.2],[0.1, 0.1, 0.25]])
A

matrix([[0.25, 0.2 , 0.1 ],
        [0.1 , 0.25, 0.2 ],
        [0.1 , 0.1 , 0.25]])

In [3]:
#Goal vector
g = np.transpose(np.matrix([0.05, 0.15, 0.05]))
g

matrix([[0.05],
        [0.15],
        [0.05]])

In [5]:
# solve x = Ax + g
xT1 = np.linalg.solve(np.identity(3) - A,g)

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT1))

Expected Threat
Central, Box, Wing
[[0.14991763 0.25205931 0.12026359]]


In [7]:
xT2=np.zeros((3,1))
for t in range(10):
   xT2 = np.matmul(A,xT2) + g

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT2))

Expected Threat
Central, Box, Wing
[[0.14966911 0.25182476 0.12007973]]


In [9]:
num_sims=100
xT3=np.zeros(3)

description = {0: 'Central', 1: 'Wing', 2: 'Box' }

for i in range(3):
    num_goals = 0

    print('---------------')
    print('Start from ' + description[i] )
    print('---------------')

    for n in range(num_sims):

        ballinplay=True
        #Initial state is i
        s = i
        describe_possession=''

        while ballinplay:
            r=np.random.rand()

            # Make commentary text
            describe_possession = describe_possession + ' - ' + description[s]


            #Cumulative sum of in play probabilities
            c_sum=np.cumsum(A[s,:])
            new_s = np.sum(r>c_sum)
            if new_s>2:
                #Ball is either goal or out of play
                ballinplay=False
                if r < g[s] + c_sum[0,2]:
                    #Its a goal!
                    num_goals = num_goals + 1
                    describe_possession = describe_possession + ' - Goal!'
                else:
                    describe_possession = describe_possession + ' - Out of play'
            s = new_s

        print(describe_possession)

    xT3[i] = num_goals/num_sims


print('\n\n---------------')
print('Expected Threat')
print('Central, Box, Wing')
print(xT3)

---------------
Start from Central
---------------
 - Central - Out of play
 - Central - Central - Out of play
 - Central - Central - Box - Wing - Goal!
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Central - Out of play
 - Central - Central - Box - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Central - Wing - Out of play
 - Central - Wing - Out of play
 - Central - Central - Out of play
 - Central - Out of play
 - Central - Central - Out of play
 - Central - Central - Central - Out of play
 - Central - Central - Out of play
 - Central - Central - Wing - Box - Out of play
 - Central - Box - Box - Box - Out of play
 - Central - Wing - Wing - Box - Box - Out of play
 - Central - Wing - Goal!
 - Central - Central - Box - Out of play
 - Central - Wing - Out of play
 - Central - Out of play
 - Central - Out of play
 - Central - Central - Central 